# Generated by Django 5.2.15 on 2026-07-25 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0003_document_deleted_at_document_deleted_by_and_more"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_code", models.CharField(max_length=80, verbose_name="章节编码")),
                ("title", models.CharField(max_length=255, verbose_name="章节标题")),
                ("content", models.TextField(verbose_name="可编辑正文")),
                (
                    "structured_content",
                    models.JSONField(default=dict, verbose_name="结构化正文"),
                ),
                ("citations", models.JSONField(default=list, verbose_name="引用")),
                (
                    "validation_issues",
                    models.JSONField(default=list, verbose_name="校验问题"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=1, verbose_name="修订号"),
                ),
                ("is_locked", models.BooleanField(default=False, verbose_name="锁定")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "四措两案生成章节",
                "verbose_name_plural": "四措两案生成章节",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="模板编码")),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=120, verbose_name="甲方名称"),
                ),
                (
                    "business_type",
                    models.CharField(
                        default="wind_turbine_inspection_four_measures_two_plans",
                        max_length=80,
                        verbose_name="业务类型",
                    ),
                ),
                ("version", models.CharField(max_length=50, verbose_name="模板版本")),
                (
                    "field_mapping",
                    models.JSONField(blank=True, default=dict, verbose_name="字段映射"),
                ),
                ("section_order", models.JSONField(default=list, verbose_name="章节顺序")),
                (
                    "required_fact_fields",
                    models.JSONField(default=list, verbose_name="必填事实字段"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="启用")),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("approved", "已批准")],
                        default="draft",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_generation_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_generation_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_templates",
                        to="documents.documentversion",
                        verbose_name="模板文件版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "四措两案模板",
                "verbose_name_plural": "四措两案模板",
                "ordering": ["client_name", "code", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GenerationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_purpose",
                    models.CharField(
                        default="entry_four_measures_two_plans",
                        editable=False,
                        max_length=80,
                        verbose_name="文档用途",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        default="wind_turbine_inspection_four_measures_two_plans",
                        max_length=80,
                        verbose_name="业务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("extracting", "提取事实"),
                            ("needs_confirmation", "待确认事实"),
                            ("ready", "可生成"),
                            ("queued", "已排队"),
                            ("generating", "生成中"),
                            ("review_required", "待审核"),
                            ("approved", "已批准"),
                            ("exported", "已导出"),
                            ("failed", "失败"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(default=0, verbose_name="进度"),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=120, verbose_name="创建幂等键"),
                ),
                (
                    "request_fingerprint",
                    models.CharField(max_length=64, verbose_name="请求指纹"),
                ),
                ("facts_snapshot", models.JSONField(default=list, verbose_name="事实快照")),
                ("fact_conflicts", models.JSONField(default=list, verbose_name="事实冲突")),
                ("risk_profile", models.JSONField(default=dict, verbose_name="风险画像")),
                (
                    "pending_section_codes",
                    models.JSONField(default=list, verbose_name="待生成章节"),
                ),
                (
                    "provider_alias",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Provider"
                    ),
                ),
                (
                    "model_alias",
                    models.CharField(blank=True, max_length=120, verbose_name="模型"),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Prompt版本"
                    ),
                ),
                (
                    "chunk_rule_version",
                    models.CharField(blank=True, max_length=80, verbose_name="切分规则版本"),
                ),
                (
                    "generation_attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="生成尝试次数"),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=80, verbose_name="错误码"),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, verbose_name="错误说明"),
                ),
                (
                    "draft_storage_path",
                    models.CharField(blank=True, max_length=500, verbose_name="草稿存储路径"),
                ),
                (
                    "draft_sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="草稿SHA-256"
                    ),
                ),
                (
                    "draft_filename",
                    models.CharField(blank=True, max_length=255, verbose_name="草稿文件名"),
                ),
                (
                    "export_idempotency_key",
                    models.CharField(blank=True, max_length=120, verbose_name="导出幂等键"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="批准时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始生成时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="生成完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_generation_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "output_document_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_outputs",
                        to="documents.documentversion",
                        verbose_name="正式导出版本",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_tasks",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_generation_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_tasks",
                        to="document_generation.documenttemplate",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "四措两案生成任务",
                "verbose_name_plural": "四措两案生成任务",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GenerationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_sha256",
                    models.CharField(max_length=64, verbose_name="文件SHA-256"),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "待解析"),
                            ("parsed", "已解析"),
                            ("failed", "解析失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="解析状态",
                    ),
                ),
                (
                    "parse_error",
                    models.CharField(blank=True, max_length=500, verbose_name="解析错误"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_sources",
                        to="documents.documentversion",
                        verbose_name="来源文档版本",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="document_generation.generationtask",
                        verbose_name="生成任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "四措两案生成来源",
                "verbose_name_plural": "四措两案生成来源",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GenerationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("facts_confirmed", "事实已确认"),
                            ("section_edited", "章节已编辑"),
                            ("section_locked", "章节已锁定"),
                            ("section_unlocked", "章节已解锁"),
                            ("section_regenerated", "章节重新生成"),
                            ("submitted", "提交审核"),
                            ("approved", "批准"),
                            ("exported", "导出"),
                            ("retried", "重试"),
                        ],
                        max_length=40,
                        verbose_name="动作",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="意见")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="附加信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="document_generation.generatedsection",
                        verbose_name="章节",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="document_generation.generationtask",
                        verbose_name="生成任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "四措两案审核记录",
                "verbose_name_plural": "四措两案审核记录",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="generatedsection",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="document_generation.generationtask",
                verbose_name="生成任务",
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_id",
                    models.CharField(max_length=120, unique=True, verbose_name="知识块编码"),
                ),
                (
                    "business_type",
                    models.CharField(
                        default="wind_turbine_inspection_four_measures_two_plans",
                        max_length=80,
                        verbose_name="业务类型",
                    ),
                ),
                (
                    "client_code",
                    models.CharField(blank=True, max_length=80, verbose_name="甲方编码"),
                ),
                ("section_code", models.CharField(max_length=80, verbose_name="章节编码")),
                ("heading_path", models.JSONField(default=list, verbose_name="标题路径")),
                (
                    "paragraph_start",
                    models.PositiveIntegerField(default=0, verbose_name="起始段落"),
                ),
                (
                    "paragraph_end",
                    models.PositiveIntegerField(default=0, verbose_name="结束段落"),
                ),
                ("locator", models.JSONField(default=dict, verbose_name="来源定位")),
                ("text", models.TextField(verbose_name="正文")),
                (
                    "content_sha256",
                    models.CharField(max_length=64, verbose_name="正文SHA-256"),
                ),
                ("component_tags", models.JSONField(default=list, verbose_name="部件标签")),
                ("method_tags", models.JSONField(default=list, verbose_name="方法标签")),
                ("risk_tags", models.JSONField(default=list, verbose_name="风险标签")),
                ("embedding", models.JSONField(default=list, verbose_name="向量")),
                (
                    "embedding_model_alias",
                    models.CharField(max_length=120, verbose_name="向量模型"),
                ),
                (
                    "embedding_dimension",
                    models.PositiveIntegerField(verbose_name="向量维度"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="启用")),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("approved", "已批准")],
                        default="draft",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_generation_knowledge",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "source_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_knowledge_sections",
                        to="documents.documentversion",
                        verbose_name="来源文档版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "四措两案知识章节",
                "verbose_name_plural": "四措两案知识章节",
                "ordering": ["business_type", "section_code", "chunk_id"],
            },
        ),
        migrations.CreateModel(
            name="ClauseBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80, verbose_name="条款编码")),
                ("version", models.CharField(max_length=50, verbose_name="条款版本")),
                (
                    "business_type",
                    models.CharField(
                        default="wind_turbine_inspection_four_measures_two_plans",
                        max_length=80,
                        verbose_name="业务类型",
                    ),
                ),
                ("section_code", models.CharField(max_length=80, verbose_name="章节编码")),
                ("text", models.TextField(verbose_name="条款正文")),
                (
                    "risk_conditions",
                    models.JSONField(default=list, verbose_name="风险适用条件"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="启用")),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("approved", "已批准")],
                        default="draft",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_generation_clauses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_generation_clauses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "四措两案批准条款",
                "verbose_name_plural": "四措两案批准条款",
                "ordering": ["section_code", "code", "-id"],
                "indexes": [
                    models.Index(
                        fields=["business_type", "section_code", "is_active"],
                        name="docgen_clause_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "version"), name="docgen_clause_code_ver_uq"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["business_type", "is_active", "approval_status"],
                name="docgen_tpl_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                fields=("code", "version"), name="docgen_template_code_ver_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(
                fields=["project", "status"], name="docgen_task_project_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(
                fields=["status", "updated_at"], name="docgen_task_recovery_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtask",
            constraint=models.UniqueConstraint(
                fields=("created_by", "idempotency_key"),
                name="docgen_task_actor_idem_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("document_purpose", "entry_four_measures_two_plans")
                ),
                name="docgen_task_purpose_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtask",
            constraint=models.CheckConstraint(
                condition=models.Q(("progress__gte", 0), ("progress__lte", 100)),
                name="docgen_task_progress_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="generationsource",
            index=models.Index(
                fields=["task", "parse_status"], name="docgen_source_parse_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationsource",
            constraint=models.UniqueConstraint(
                fields=("task", "document_version"), name="docgen_source_task_ver_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="generationreview",
            index=models.Index(
                fields=["task", "action"], name="docgen_review_action_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedsection",
            index=models.Index(
                fields=["task", "is_locked"], name="docgen_section_lock_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedsection",
            constraint=models.UniqueConstraint(
                fields=("task", "section_code"), name="docgen_section_task_code_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesection",
            index=models.Index(
                fields=["business_type", "section_code", "is_active"],
                name="docgen_knowledge_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesection",
            index=models.Index(
                fields=["embedding_model_alias", "embedding_dimension"],
                name="docgen_knowledge_emb_idx",
            ),
        ),
    ]
