# Generated by Django 5.2.15 on 2026-07-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationtask",
            name="operation",
            field=models.CharField(
                choices=[("extract", "提取事实"), ("generate", "生成文档")],
                default="extract",
                max_length=20,
                verbose_name="当前操作",
            ),
        ),
    ]
