# Generated by Django 5.2.15 on 2026-07-28 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_generation", "0004_alter_generationtask_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generationtask",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_generation_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AlterField(
            model_name="generationreview",
            name="action",
            field=models.CharField(
                choices=[
                    ("facts_confirmed", "事实已确认"),
                    ("section_edited", "章节已编辑"),
                    ("section_locked", "章节已锁定"),
                    ("section_unlocked", "章节已解锁"),
                    ("section_regenerated", "章节重新生成"),
                    ("submitted", "提交审核"),
                    ("approved", "批准"),
                    ("exported", "导出"),
                    ("retried", "重试"),
                    ("stopped", "停止"),
                ],
                max_length=40,
                verbose_name="动作",
            ),
        ),
        migrations.AlterField(
            model_name="generationtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("extracting", "提取事实"),
                    ("needs_confirmation", "待确认事实"),
                    ("ready", "可生成"),
                    ("queued", "已排队"),
                    ("generating", "生成中"),
                    ("review_required", "待审核"),
                    ("pending_approval", "待批准"),
                    ("approved", "已批准"),
                    ("exported", "已导出"),
                    ("failed", "失败"),
                    ("cancelled", "已停止"),
                ],
                default="draft",
                max_length=30,
                verbose_name="状态",
            ),
        ),
    ]
