# Generated by Django 5.2.15 on 2026-07-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_generation", "0005_generationtask_deleted_at_generationtask_deleted_by_and_more"),
        ("documents", "0004_document_source_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCorpusUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        default="wind_turbine_inspection_four_measures_two_plans",
                        max_length=80,
                        verbose_name="业务类型",
                    ),
                ),
                ("client_code", models.CharField(blank=True, max_length=80, verbose_name="甲方编码")),
                (
                    "section_code",
                    models.CharField(
                        choices=[
                            ("overview", "工程概况与编制依据"),
                            ("organization_measures", "组织措施"),
                            ("construction_plan", "施工方案"),
                            ("technical_measures", "技术措施"),
                            ("safety_measures", "安全措施"),
                            ("risk_identification", "风险辨识与预控"),
                            ("emergency_plan", "应急预案"),
                            ("environmental_measures", "环境保护与文明施工"),
                        ],
                        max_length=80,
                        verbose_name="适用章节",
                    ),
                ),
                ("component_tags", models.JSONField(blank=True, default=list, verbose_name="部件标签")),
                ("method_tags", models.JSONField(blank=True, default=list, verbose_name="方法标签")),
                ("risk_tags", models.JSONField(blank=True, default=list, verbose_name="风险标签")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "等待处理"),
                            ("processing", "正在处理"),
                            ("succeeded", "已入库"),
                            ("failed", "处理失败"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("chunk_count", models.PositiveIntegerField(default=0, verbose_name="知识块数量")),
                ("embedding_model_alias", models.CharField(blank=True, max_length=120, verbose_name="向量模型")),
                ("embedding_dimension", models.PositiveIntegerField(blank=True, null=True, verbose_name="向量维度")),
                ("error_code", models.CharField(blank=True, max_length=80, verbose_name="错误码")),
                ("error_message", models.CharField(blank=True, max_length=500, verbose_name="错误说明")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始处理时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="处理完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_generation_corpus_uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
                (
                    "source_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_corpus_uploads",
                        to="documents.documentversion",
                        verbose_name="来源文档版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG语料上传",
                "verbose_name_plural": "RAG语料上传",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="docgen_corpus_status_idx"),
                    models.Index(
                        fields=["business_type", "section_code"],
                        name="docgen_corpus_section_idx",
                    ),
                ],
            },
        ),
    ]
