# Generated by Django 5.2.15 on 2026-08-09 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


TABLE_HEADER_TERMS = (
    "姓名",
    "人员",
    "危险源",
    "危险点",
    "控制措施",
    "工序",
    "检测点",
    "检测项目",
    "工具",
    "仪器",
    "安全器材",
    "劳保",
    "防护用品",
)


def backfill_recoverable_table_chunks(apps, schema_editor):
    KnowledgeSection = apps.get_model("document_generation", "KnowledgeSection")
    for row in KnowledgeSection.objects.filter(text__contains=" | ").iterator():
        lines = [line.strip() for line in row.text.splitlines() if line.strip()]
        if len(lines) < 2 or not all(" | " in line for line in lines):
            continue
        values = [[cell.strip() for cell in line.split(" | ")] for line in lines]
        if len({len(value) for value in values}) != 1 or not values[0]:
            continue
        header = " ".join(values[0])
        if not any(term in header for term in TABLE_HEADER_TERMS):
            continue
        row.block_type = "table"
        row.structured_content = {"rows": values, "recovered_from": "legacy_pipe_text"}
        row.save(update_fields=["block_type", "structured_content"])


class Migration(migrations.Migration):

    dependencies = [
        ("document_generation", "0009_agentsystemprompt_generationtask_system_prompt"),
        ("documents", "0004_document_source_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="layout_schema",
            field=models.JSONField(blank=True, default=dict, verbose_name="结构化版式定义"),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="completion_state",
            field=models.CharField(
                choices=[("complete", "内容完整"), ("pending_manual_fill", "待人工补录")],
                default="complete",
                max_length=30,
                verbose_name="内容完整状态",
            ),
        ),
        migrations.AddField(
            model_name="knowledgesection",
            name="block_type",
            field=models.CharField(default="text", max_length=20, verbose_name="内容块类型"),
        ),
        migrations.AddField(
            model_name="knowledgesection",
            name="structured_content",
            field=models.JSONField(blank=True, default=dict, verbose_name="结构化内容"),
        ),
        migrations.RunPython(backfill_recoverable_table_chunks, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ApprovedDocumentIllustration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="名称")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("height_escape_plan", "高空应急逃生预案图"),
                            ("height_rescue_plan", "高空应急救援预案图"),
                        ],
                        max_length=40,
                        verbose_name="图片类型",
                    ),
                ),
                ("caption", models.CharField(max_length=300, verbose_name="图注")),
                ("alt_text", models.CharField(max_length=300, verbose_name="替代文本")),
                (
                    "applicability",
                    models.JSONField(blank=True, default=dict, verbose_name="适用条件"),
                ),
                (
                    "width_px",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="像素宽度"
                    ),
                ),
                (
                    "height_px",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="像素高度"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        verbose_name="图片SHA-256",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="启用")),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("approved", "已批准")],
                        default="draft",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_generation_illustrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_generation_illustrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_generation_illustrations",
                        to="documents.documentversion",
                        verbose_name="图片文件版本",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "title", "id"],
            },
        ),
        migrations.CreateModel(
            name="GenerationTaskAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rescue_route", "救援路线图"),
                            ("height_escape_plan", "高空应急逃生预案图"),
                            ("height_rescue_plan", "高空应急救援预案图"),
                        ],
                        max_length=40,
                        verbose_name="图片类型",
                    ),
                ),
                ("storage_path", models.CharField(max_length=500, verbose_name="存储路径")),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                ("media_type", models.CharField(max_length=80, verbose_name="媒体类型")),
                ("sha256", models.CharField(max_length=64, verbose_name="图片SHA-256")),
                ("width_px", models.PositiveIntegerField(verbose_name="像素宽度")),
                ("height_px", models.PositiveIntegerField(verbose_name="像素高度")),
                ("caption", models.CharField(max_length=300, verbose_name="图注")),
                ("alt_text", models.CharField(max_length=300, verbose_name="替代文本")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="冻结信息"),
                ),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_illustration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_assets",
                        to="document_generation.approveddocumentillustration",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_generation_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="document_generation.generationtask",
                    ),
                ),
            ],
            options={
                "ordering": ["task_id", "kind"],
            },
        ),
        migrations.AddIndex(
            model_name="approveddocumentillustration",
            index=models.Index(
                fields=["kind", "is_active", "approval_status"],
                name="docgen_illus_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationtaskasset",
            constraint=models.UniqueConstraint(
                fields=("task", "kind"), name="docgen_task_asset_kind_uq"
            ),
        ),
    ]
