# Generated by Django 5.2.15 on 2026-06-24 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="项目名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="项目编号"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "进行中"), ("archived", "已归档")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="归档时间"),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="归档人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目负责人",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "负责人"),
                            ("operator", "资料整理员"),
                            ("viewer", "查看者"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="项目角色",
                    ),
                ),
                ("can_upload", models.BooleanField(default=False, verbose_name="可上传")),
                (
                    "can_download_restricted",
                    models.BooleanField(default=False, verbose_name="可下载受限文件"),
                ),
                (
                    "can_manage_folder",
                    models.BooleanField(default=False, verbose_name="可管理文件夹"),
                ),
                ("can_delete", models.BooleanField(default=False, verbose_name="可删除")),
                ("can_restore", models.BooleanField(default=False, verbose_name="可恢复")),
                (
                    "can_manage_permission",
                    models.BooleanField(default=False, verbose_name="可管理授权"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目成员",
                "verbose_name_plural": "项目成员",
                "ordering": ["project_id", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="project_status_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["manager"], name="project_manager_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["created_at"], name="project_created_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(fields=["project", "role"], name="member_project_role_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(fields=["user"], name="member_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="unique_project_member"
            ),
        ),
    ]
