# Generated by Django 5.2.15 on 2026-07-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemBackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("scheduled", "计划任务"), ("manual", "手动")],
                        max_length=20,
                        verbose_name="触发方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "执行中"), ("success", "成功"), ("failure", "失败")],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "local_path",
                    models.CharField(blank=True, max_length=1000, verbose_name="服务器本机备份路径"),
                ),
                (
                    "offsite_path",
                    models.CharField(blank=True, max_length=1000, verbose_name="可选离机副本路径"),
                ),
                ("sha256", models.CharField(blank=True, max_length=64, verbose_name="SHA-256")),
                ("size_bytes", models.PositiveBigIntegerField(default=0, verbose_name="备份大小")),
                ("error_message", models.TextField(blank=True, verbose_name="失败原因")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_backup_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统备份记录",
                "verbose_name_plural": "系统备份记录",
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "started_at"],
                        name="system_backup_status_idx",
                    ),
                    models.Index(fields=["started_at"], name="system_backup_started_idx"),
                ],
            },
        ),
    ]
