# Generated by Django 5.2.15 on 2026-06-25 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                ("message", models.TextField(verbose_name="内容")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "系统"),
                            ("document", "文档"),
                            ("access", "授权"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="分类",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=80, verbose_name="资源类型"),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=80, verbose_name="资源 ID"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收人",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["recipient", "is_read"], name="notif_recipient_read_idx"),
                    models.Index(fields=["created_at"], name="notif_created_idx"),
                ],
            },
        ),
    ]
