# Generated by Django 5.2.15 on 2026-06-24 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="动作")),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=100, verbose_name="资源类型"),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=100, verbose_name="资源 ID"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failure", "失败"),
                            ("denied", "拒绝"),
                        ],
                        max_length=20,
                        verbose_name="结果",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 地址"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "request_id",
                    models.CharField(blank=True, max_length=64, verbose_name="请求 ID"),
                ),
                (
                    "before_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更前"),
                ),
                (
                    "after_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更后"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误原因")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["created_at"], name="audit_created_at_idx"),
                    models.Index(fields=["action"], name="audit_action_idx"),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_resource_idx",
                    ),
                    models.Index(fields=["user"], name="audit_user_idx"),
                ],
            },
        ),
    ]
