# Generated by Django 5.2.15 on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_admin", "系统管理员"),
                    ("project_manager", "项目负责人"),
                    ("data_operator", "资料整理员"),
                    ("temporary_user", "临时用户"),
                ],
                default="data_operator",
                max_length=32,
                verbose_name="角色",
            ),
        ),
    ]
