# Generated by Django 5.2.15 on 2026-06-24 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("folders", "0002_folder_is_system_root"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="access_level",
            field=models.CharField(
                choices=[("internal", "内部"), ("restricted", "受限")],
                default="internal",
                max_length=20,
                verbose_name="访问级别",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["access_level"], name="document_access_level_idx"),
        ),
    ]
