# Generated by Django 5.2.15 on 2026-06-25 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_document_access_level_and_more"),
        ("folders", "0002_folder_is_system_root"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="lock_version",
            field=models.PositiveIntegerField(default=1, verbose_name="乐观锁版本"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["deleted_at"], name="document_deleted_at_idx"),
        ),
    ]
