# Generated by Django 5.2.15 on 2026-06-24 08:24

from django.db import migrations, models

DEFAULT_PUBLIC_ROOTS = [
    "完工资料档案",
    "公司资质",
    "人员资质",
    "工器具年检资质",
    "劳动防护用品资料",
    "仪器设备年检资质",
    "车辆年检及资质",
]


def mark_default_public_roots(apps, schema_editor):
    folder = apps.get_model("folders", "Folder")
    folder.objects.filter(
        project__isnull=True,
        parent__isnull=True,
        name__in=DEFAULT_PUBLIC_ROOTS,
    ).update(is_system_root=True)


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_system_root",
            field=models.BooleanField(default=False, verbose_name="系统根分类"),
        ),
        migrations.RunPython(mark_default_public_roots, migrations.RunPython.noop),
    ]
