# Generated by Django 5.2.15 on 2026-06-24 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0002_document_access_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view", models.BooleanField(default=False, verbose_name="可查看")),
                (
                    "can_download",
                    models.BooleanField(default=False, verbose_name="可下载"),
                ),
                ("can_update", models.BooleanField(default=False, verbose_name="可更新")),
                ("can_delete", models.BooleanField(default=False, verbose_name="可删除")),
                ("can_restore", models.BooleanField(default=False, verbose_name="可恢复")),
                (
                    "can_manage",
                    models.BooleanField(default=False, verbose_name="可管理授权"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="撤销时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_document_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授权人",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="documents.document",
                        verbose_name="文档",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_document_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="撤销人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被授权用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档授权",
                "verbose_name_plural": "文档授权",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["document", "user"], name="grant_document_user_idx"),
                    models.Index(fields=["user", "revoked_at"], name="grant_user_revoked_idx"),
                    models.Index(fields=["expires_at"], name="grant_expires_idx"),
                ],
            },
        ),
    ]
