# Generated by Django 5.2.15 on 2026-06-25 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
        ("documents", "0002_document_access_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryAccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(max_length=64, unique=True, verbose_name="Token 哈希"),
                ),
                (
                    "max_downloads",
                    models.PositiveIntegerField(default=1, verbose_name="最大下载次数"),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="已使用次数"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="撤销时间"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后使用时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_temporary_access_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_access_grants",
                        to="documents.documentversion",
                        verbose_name="文档版本",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_temporary_access_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="撤销人",
                    ),
                ),
            ],
            options={
                "verbose_name": "临时访问授权",
                "verbose_name_plural": "临时访问授权",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["document_version", "revoked_at"],
                        name="temp_document_revoked_idx",
                    ),
                    models.Index(fields=["expires_at"], name="temp_expires_idx"),
                    models.Index(fields=["created_by"], name="temp_created_by_idx"),
                ],
            },
        ),
    ]
